name: 'React-Native tagging'
description: 'An action for automating react native versions'
inputs:
  github-auth-token:  # id of input
    description: 'Auth token for user that will be publishing release'
    required: true
  branch-to-tag:
    description: 'Name of branch to create the tag off of'
    required: true
    default: 'main'
  version-change-type:
    description: 'Type of version bump (major, minor, patch, none)'
    required: true
    default: 'none'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'