name: 'React-Native tagging'
description: 'An action for automating react native versions'
inputs:
  github-auth-token:
    description: 'A personal access token for the user that will be tagging and publishing the releases'
    required: true
  branch-to-tag:
    description: 'The name of the branch the tag should be created off of'
    required: true
    default: 'main'
  version-change-type:
    description: 'Type of version change to make (major, minor, patch, none)'
    required: true
    default: 'none'
runs:
  using: 'node12'
  main: 'index.js'