name: Tag
on:
  workflow_dispatch:
    inputs:
      versionChangeType:
        description: 'Type of version bump (major, minor, patch, none)'
        required: true
        default: 'none'

jobs:
  create-new-tag:
    name: Create new tag with version bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          github-auth-token: ${{ secrets.AUTH_TOKEN_GITHUB }}
          branch-to-tag: 'master'
          version-change-type: ${{ github.event.inputs.versionChangeType }}